import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Link from 'next/link'
import CardSection from '../components/CardSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Textr AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-bg'>
        <Header/>
        <section className=' flex justify-center'>
          <div className='h-full  w-[80%] flex items-center flex-col'>
            <div className='w-1/2 flex items-center justify-center '>
            <img src="./home.svg" alt=""  style={{'width':"27rem"}}/>
            </div>
            <div className='text-white font-semibold text-6xl'>
              Write Bette<span className='text-button'>r</span> With Text<span className='text-button'>r</span>
            </div>
            <div className='py-4 text-white text-2xl font-semibold w-3/4 max-w-[60rem] navlinks'>
            <p className='text-center'> With our <span className='text-button'>AI writing assistant</span>, you can generate high-quality content in a matter of seconds.Simply enter your desired topic and the AI will do the rest, providing you with a polished,<span className='text-button'>professional-quality piece of writing.</span></p>
            <div className='py-4 w-full grid grid-flow-col gap-8 navlinks'>
              <button className='text-white navlinks text-lg  h-min font-semibold bg-button rounded-2xl px-4 py-2 w-48 items-end ml-auto shadow-btn'>Try For Free</button>
              <span className='text-lg pt-2'><Link href="#">Book A Demo</Link></span>
            </div>
            </div>
          </div>
        </section>
        <section className='w-screen bg-red-400'>
            <CardSection></CardSection>
        </section>
      </main>
    </>
  )
}
